package com.msrtc.portal.applicant.domain;

public enum PostEnum {

    DRIVER_JR(1), CONDUCTOR_JR(2), CLERKTYPIST_JR(3), ASSISTANT_JR(4), ASSISTANTTRAFFICSUPERINTENDENT_JR(5), TRAFFIC_INSPECTOR_JR(6), 
    ACCOUNTANTJRSTOCKVERIFIER_JR(7), STORESUPERVISRSRSTOCKVERIFIER_JR(8), STOREKEEPER_JR(9), SECURITYINSPECTOR_JR(10), ASSISTANTSECURITYINSPECTOR_JR(11),
    FIREWARDEN(12), JUNIORENGINEERCIVIL_JR(13), JUNIORENGINEERELECTRICAL_JR(14), ASSISTANTWORKSHOPSUPERINTENDENT_JR(15), CHARGEMAN_JR(16), DRAFTSMANMECHANICS_JR(17),
    SRCOMPUTEROPERATOR_JR(18), GENERALMANAGERPROJECT(19), GENERALMANAGERIT(20), DRIVERCUMCONDUCTOR_JR(21);

    private  int postId;

    PostEnum(int postId){
        this.postId = postId;
    }

    public int getPostId() {
        return postId;
    }
}
